src/Entity/Activity.php
<?php

namespace App\Entity;

use App\EntityListener\ActivityListener;
use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ActivityRepository::class)]
#[ORM\EntityListeners([ActivityListener::class])]
#[ORM\UniqueConstraint(columns: ['name', 'starting_date', 'place_id', 'organizer_id'])]
#[UniqueEntity(fields: ['name', 'starting_date', 'place'], message: "Une sortie identique est déjà proposée !")]
class Activity
{

    private const IS_ARCHIVED = false;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    #[Assert\Type(type: 'string', message: "Veuillez renseigner une chaine de caractère")]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    #[Assert\Length(
        min: 3,
        minMessage: "C'est trop court, il faut {{ limit }} caractère minimum",
        max: 30,
        maxMessage: "C'est trop long, il faut {{ limit }} caractère maximum",
    )]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\Type(type: "\DateTimeInterface", message: 'Veuillez saisir une date valide')]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    #[Assert\GreaterThan(value: 'today', message: "Veuillez saisir une date postérieure à celle d'aujourd'hui")]
    private ?\DateTimeInterface $starting_date = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Type(type: 'int', message: "Veuillez renseigner un nombre")]
    #[Assert\Range(min:0, max: 24, notInRangeMessage: "L'activité ne peut pas durer plus de 24 heures")]
    private ?int $duration_hours = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\Type(type: "\DateTimeInterface", message: 'Veuillez saisir une date valide')]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    #[Assert\LessThan(propertyPath: 'starting_date', message: "Veuillez saisir une date antérieure à celle du départ de l'activité")]
    private ?\DateTimeInterface $registration_limit_date = null;

    #[ORM\Column]
    #[Assert\Type(type: 'int', message: "Veuillez renseigner un nombre")]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?int $registration_max_nb = null;

    #[ORM\Column(length: 500, nullable: true)]
    #[Assert\Type(type: 'string', message: "Veuillez renseigner une chaine de caractère")]
    #[Assert\Length(
        max: 500,
        maxMessage: "C'est trop long, il faut {{ limit }} caractère maximum",
    )]
    private ?string $description = null;

    #[ORM\Column(length: 250, nullable: true)]
    #[Assert\Type(type: 'string', message: "Veuillez renseigner une chaine de caractère")]
    #[Assert\Length(
        max: 250,
        maxMessage: "C'est trop long, il faut {{ limit }} caractère maximum",
    )]
    private ?string $photo_url = null;

    #[ORM\Column]
    #[Assert\Type('bool')]
    private ?bool $is_archived = self::IS_ARCHIVED;

    #[ORM\ManyToOne(inversedBy: 'activities_organizer')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $organizer = null;

    #[ORM\ManyToOne(inversedBy: 'activities')]
    #[ORM\JoinColumn(name: 'place_id', nullable: false)]
    private ?Place $place = null;

    #[ORM\ManyToOne(inversedBy: 'activities')]
    #[ORM\JoinColumn(name: 'state_id', nullable: false)]
    private ?State $state = null;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'activity')]
    private Collection $registrations;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $cancelReason = null;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartingDate(): ?\DateTimeInterface
    {
        return $this->starting_date;
    }

    public function setStartingDate(\DateTimeInterface $starting_date): static
    {
        $this->starting_date = $starting_date;

        return $this;
    }

    public function getDurationHours(): ?int
    {
        return $this->duration_hours;
    }

    public function setDurationHours(?int $duration): static
    {
        $this->duration_hours = $duration;

        return $this;
    }

    public function getRegistrationLimitDate(): ?\DateTimeInterface
    {
        return $this->registration_limit_date;
    }

    public function setRegistrationLimitDate(\DateTimeInterface $registration_limit_date): static
    {
        $this->registration_limit_date = $registration_limit_date;

        return $this;
    }

    public function getRegistrationMaxNb(): ?int
    {
        return $this->registration_max_nb;
    }

    public function setRegistrationMaxNb(int $registration_max_nb): static
    {
        $this->registration_max_nb = $registration_max_nb;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photo_url;
    }

    public function setPhotoUrl(?string $photo_url): static
    {
        $this->photo_url = $photo_url;

        return $this;
    }

    public function isArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setArchived(bool $is_archived): static
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    public function getOrganizer(): ?User
    {
        return $this->organizer;
    }

    public function setOrganizer(?User $organizer): static
    {
        $this->organizer = $organizer;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): static
    {
        $this->state = $state;

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): static
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setActivity($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): static
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getActivity() === $this) {
                $registration->setActivity(null);
            }
        }

        return $this;
    }

    public function getCancelReason(): ?string
    {
        return $this->cancelReason;
    }

    public function setCancelReason(?string $cancelReason): static
    {
        $this->cancelReason = $cancelReason;

        return $this;
    }
}

src/Entity/State.php
<?php

namespace App\Entity;

use App\Repository\StateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StateRepository::class)]
class State
{

    private const DEFAULT_STATE = "DRAFT";

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $name = self::DEFAULT_STATE;

    /**
     * @var Collection<int, Activity>
     */
    #[ORM\OneToMany(targetEntity: Activity::class, mappedBy: 'state')]
    private Collection $activities;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $name_fr = null;

    public function __construct()
    {
        $this->activities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): static
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->setState($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): static
    {
        if ($this->activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getState() === $this) {
                $activity->setState(null);
            }
        }

        return $this;
    }

    public function getNameFr(): ?string
    {
        return $this->name_fr;
    }

    public function setNameFr(?string $name_fr): static
    {
        $this->name_fr = $name_fr;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_PSEUDO', fields: ['pseudo'])]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: 'pseudo', message: 'Pseudo déjà utilisé')]
#[UniqueEntity(fields: 'email', message: 'E-mail déjà utilisé')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, EquatableInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $pseudo = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 30)]
    private ?string $last_name = null;

    #[ORM\Column(length: 30)]
    private ?string $first_name = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $is_active = true;

    /**
     * @var Collection<int, Activity>
     */
    #[ORM\OneToMany(targetEntity: Activity::class, mappedBy: 'organizer', orphanRemoval: true)]
    private Collection $activities_organizer;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'user')]
    private Collection $registrations;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Campus $campus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profileImage = null;

    public function __construct()
    {
        $this->activities_organizer = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivitiesOrganizer(): Collection
    {
        return $this->activities_organizer;
    }

    public function addActivityOrganizer(Activity $activity): static
    {
        if (!$this->activities_organizer->contains($activity)) {
            $this->activities_organizer->add($activity);
            $activity->setOrganizer($this);
        }

        return $this;
    }

    public function removeActivityOrganizer(Activity $activity): static
    {
        if ($this->activities_organizer->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getOrganizer() === $this) {
                $activity->setOrganizer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): static
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setUser($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): static
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getUser() === $this) {
                $registration->setUser(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): static
    {
        $this->campus = $campus;

        return $this;
    }

    public function getProfileImage(): ?string
    {
        return $this->profileImage;
    }

    public function setProfileImage(?string $profileImage): static
    {
        $this->profileImage = $profileImage;

        return $this;
    }

    public function isEqualTo(UserInterface $user): bool
    {
        if (!$user instanceof User) {
            return false;
        }

        if ($this->is_active !== $user->is_active) {
            // Forces the user to log in again if enabled
            // changes from true to false or vice-versa.
            // This could be replaced by a more sophisticated comparison.
            return false;
        }

        // do a bunch of other checks, such as comparing the
        // password hash: this will cause the user to be logged
        // out when their password is changed.

        return true;
    }

}

templates/activity/_cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Sorties{% endblock %}

{% block body %}
<div class="max-w-4xl lg:max-w-3xl mx-auto bg-white-transparent p-6 rounded-lg shadow-lg">
    <h1 class="text-3xl font-extrabold text-gray-800 mb-6 text-center">Annuler la sortie</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ activity.name }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ activity.startingDate ? activity.startingDate|date('d/m/Y H:i') : ''}}</td>
            </tr>
            <tr>
                <th>Site organisateur</th>
                <td>{{ activity.organizer.campus.name }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ activity.place.name ~ ' ' ~ activity.place.city.postcode ~ ' ' ~ activity.place.city.name}}</td>
            </tr>
        </tbody>
    </table>

    {{ form_start(form) }}

    {{ form_widget(form) }}
    <div class="action-links mt-5 flex justify-center">
        <a href="{{ path('app_activity_list') }}" class="form-button my-3 mr-5 pb-0">Retour à la liste</a>
        <button class="form-button my-3 mr-5">{{ button_label|default('Confirmer') }}</button>
    </div>

    {{ form_end(form) }}

</div>
{% endblock %}

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('app_activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/activity/_form.html.twig
{{ form_start(form) }}

{{ form_widget(form) }}
<div class="action-links mt-5 flex justify-center">
    <a href="{{ path('app_activity_list') }}" class="form-button my-3 mr-5 pb-0">Retour à la liste</a>
    <button class="form-button my-3 mr-5">{{ button_label|default('Enregistrer') }}</button>

    {% if not activity.id %}
        <input class="form-button my-3 mr-5" type="submit" formaction="{{ path('app_activity_create', {'autoPublish' : 'true'}) }}" value="Publier">
    {%  endif %}
    {% if activity.state.name=='draft' %}
        <a href="{{ path('app_activity_publish',{'id':activity.id}) }}" class="form-button my-3 mr-5">Publier</a>
    {% endif %}
    {% if activity.state.name !='done' %}
        <a href="{{ path('app_activity_cancel',{'id':activity.id}) }}" class="form-button my-3 mr-5">Supprimer</a>
    {% endif %}
</div>

{{ form_end(form) }}

templates/activity/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Sorties{% endblock %}

{% block body %}
    <div class="max-w-4xl lg:max-w-3xl mx-auto bg-white-transparent p-6 rounded-lg shadow-lg">
        <h1 class="text-3xl font-extrabold text-gray-800 mb-6 text-center">Créer Sortie</h1>

        {{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {% for field in form %}
                {% if field.vars.name == '_token' %}
                    {# Rendre le champ CSRF invisible #}
                    {{ form_widget(field, {'attr': {'class': 'hidden'}}) }}
                {% else %}
                    <!-- Autres champs du formulaire -->
                    <div class="form-group mb-4">
                        {{ form_label(field, null, {'attr': {'class': 'block text-gray-700 font-medium mb-1'}}) }}
                        {{ form_widget(field, {'attr': {'class': 'form-input w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-orange-500 focus:ring-opacity-50'}}) }}
                        {{ form_errors(field, {'attr': {'class': 'text-red-600 text-sm mt-1'}}) }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="inline-block px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-md transition-colors duration-300">
                {{ button_label|default('Créer') }}
            </button>
            {% if not activity.id %}
                <button class="inline-block px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-md transition-colors duration-300" type="submit" formaction="{{ path('app_activity_create', {'autoPublish' : 'true'}) }}">Publier</button>
            {%  endif %}
        </div>

        {{ form_end(form, {'render_rest': false}) }}
    </div>
{% endblock %}

templates/activity/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Sorties{% endblock %}

{% block body %}
    <div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
        <h1 class="text-3xl font-extrabold text-gray-800 mb-4 text-center">Sortie</h1>

    {% if activity.getPhotoUrl() %}
        <div class="flex justify-center my-5 px-5">
            <img src="{{ activity.photoUrl }}" alt="profile picture" >
        </div>
    {% endif %}

    <div class="flex justify-center">

    <table class="table">
        <tbody>

            <tr>
                <th>Nom de la sortie :</th>
                <td>{{ activity.name }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ activity.state.nameFr }}</td>
            </tr>
            <tr>
                <th>Date et l'heure de la sortie :</th>
                <td>{{ activity.startingDate ? activity.startingDate|date('d/m/Y H:i') : '' }}</td>
            </tr>
            <tr>
                <th>Date limite d'inscription</th>
                <td>{{ activity.registrationLimitDate ? activity.registrationLimitDate|date('d/m/Y H:i') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre de places :</th>
                <td>{{ activity.registrationMaxNb }}</td>
            </tr>
            <tr>
                <th>Durée [heures] :</th>
                <td>{% if activity.durationHours %}
                        {{ activity.durationHours }}
                    {% else %}
                        <i>Non renseignée</i>
                    {% endif %}
                </td>
            </tr>


            <tr>
                <th>Description et infos :</th>
                <td>{{ activity.description }}</td>
            </tr>

            <tr>
                <th>Lieu :</th>
                <td>{{ activity.place.name }}</td>
            </tr>

            <tr>
                <th>Rue :</th>
                <td>{{ activity.place.street }}</td>
            </tr>

            <tr>
                <th>Ville :</th>
                <td>{{ activity.place.city.name }}</td>
            </tr>

            <tr>
                <th>Code postal :</th>
                <td>{{ activity.place.city.postcode }}</td>
            </tr>

            <tr hidden>
                <th>Latitude :</th>
                <td id="latitude">{{ activity.place.latitude }}</td>
            </tr>

            <tr hidden>
                <th>Longitude :</th>
                <td id="longitude">{{ activity.place.longitude }}</td>
            </tr>
            </tbody>
        </table>
    </div>


        <h2 style="text-align: center">Liste des participants inscrits</h2>

        <div class="flex justify-center">
        <table class="table">
            <thead>
            <tr>
                <th></th>
                <th>Pseudo</th>
                <th>Nom</th>
            </tr>
            </thead>
            <tbody>
            {% for registration in activity.registrations %}
                <tr>
                    <td><a href="{{ path('app_user_profile', {'id': registration.user.id}) }}"><img style="max-height: 30px" src="{{ asset('images/icone-afficher.webp') }}" alt="Afficher"></a></td>
                    <td>{{ registration.user.pseudo }}</td>
                    <td>{{ registration.user.firstName }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">Aucun participant pour le moment !</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>

        <div class="flex justify-center">
        <a class="btn" href="{{ path('app_activity_list') }}">Retour à la liste</a>
        </div>

        {% if activity.organizer.id == app.user.id %}
            <a class="btn" href="{{ path('app_activity_update', {'id': activity.id}) }}">Modifier</a>
        {% endif %}

        {{ include('/place/_map.html.twig') }}

    </div>


{% endblock %}

templates/activity/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Sorties{% endblock %}

{% block body %}

    <div class="max-w-4xl lg:max-w-3xl mx-auto bg-white-transparent p-6 rounded-lg shadow-lg">
        <h1 class="text-3xl font-extrabold text-gray-800 mb-6 text-center">Modifier sortie</h1>

            {{ include('activity/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    </div>
{% endblock %}