src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_PSEUDO', fields: ['pseudo'])]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: 'pseudo', message: 'Pseudo déjà utilisé')]
#[UniqueEntity(fields: 'email', message: 'E-mail déjà utilisé')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, EquatableInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $pseudo = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 30)]
    private ?string $last_name = null;

    #[ORM\Column(length: 30)]
    private ?string $first_name = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $is_active = true;

    /**
     * @var Collection<int, Activity>
     */
    #[ORM\OneToMany(targetEntity: Activity::class, mappedBy: 'organizer', orphanRemoval: true)]
    private Collection $activities_organizer;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'user')]
    private Collection $registrations;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Campus $campus = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profileImage = null;

    public function __construct()
    {
        $this->activities_organizer = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivitiesOrganizer(): Collection
    {
        return $this->activities_organizer;
    }

    public function addActivityOrganizer(Activity $activity): static
    {
        if (!$this->activities_organizer->contains($activity)) {
            $this->activities_organizer->add($activity);
            $activity->setOrganizer($this);
        }

        return $this;
    }

    public function removeActivityOrganizer(Activity $activity): static
    {
        if ($this->activities_organizer->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getOrganizer() === $this) {
                $activity->setOrganizer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): static
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setUser($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): static
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getUser() === $this) {
                $registration->setUser(null);
            }
        }

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): static
    {
        $this->campus = $campus;

        return $this;
    }

    public function getProfileImage(): ?string
    {
        return $this->profileImage;
    }

    public function setProfileImage(?string $profileImage): static
    {
        $this->profileImage = $profileImage;

        return $this;
    }

    public function isEqualTo(UserInterface $user): bool
    {
        if (!$user instanceof User) {
            return false;
        }

        if ($this->is_active !== $user->is_active) {
            // Forces the user to log in again if enabled
            // changes from true to false or vice-versa.
            // This could be replaced by a more sophisticated comparison.
            return false;
        }

        // do a bunch of other checks, such as comparing the
        // password hash: this will cause the user to be logged
        // out when their password is changed.

        return true;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Campus;
use App\Entity\Activity;
use App\Entity\User;
use App\Form\CsvUploadType;
use App\Form\RegistrationFormType;
use App\Form\UserType;
use App\Repository\CampusRepository;
use App\Repository\ActivityRepository;
use App\Repository\RegistrationRepository;
use App\Repository\UserRepository;
use Couchbase\Role;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Exception;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/user',name: 'app_user')]
class UserController extends AbstractController
{

    #[Route('/', name: '_list', methods: ['GET'])]
    #[IsGranted("ROLE_ADMIN")]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/myAccount', name: '_show', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function show(): Response
    {
        $user = $this->getUser();

        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/myAccount/edit', name: '_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function edit(Request $request, EntityManagerInterface $entityManager,UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $file */
            $file = $form->get('imageFile')->getData();
            if($file){
                if($user->getProfileImage()) {
                    /** @var UploadedFile $file */
                    $filename = $user->getProfileImage();
                    $filePath = $this->getParameter('kernel.project_dir') . '/public/profile/images/' . $filename;
                    unlink($filePath);
                }
                $filename = $file->getClientOriginalName();
                $file->move($this->getParameter('kernel.project_dir') . '/public/profile/images', $filename);
                $user->setProfileImage($filename);
            }

            // encode the plain password
            if($form->get('password')->getData()){
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $form->get('password')->getData()
                    )
                );
            }
            $entityManager->flush();
            return $this->redirectToRoute('app_home');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/profile/{id}', name: '_profile', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function organizerProfile(User $user): Response
    {

        return $this->render('user/show.html.twig', [
            'user' => $user,


        ]);
    }

//    ==================== DELETE USER ===============

    #[Route('/delete/{id}', name: '_delete', methods: ['GET'])]
    #[IsGranted("ROLE_ADMIN")]
    public function delete(
        Request $request,
        EntityManagerInterface $entityManager,
        int $id,
        UserRepository $userRepository,
        ActivityRepository $activityRepository,
        RegistrationRepository $registrationRepository
    ):  Response
    {
        $user = $userRepository->find($id);
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->get('token'))) {

            # if user have organized one or more activities
            $id = $userRepository->findIdbyPseudo('Mystery')[0]['id'];
            $activityRepository->replaceOrganizerByDummy($id, $user->getId());
            #

            # if user is register to one or more activities
            $registrationRepository->deleteUserByid($user->getId());
            #

            # Delete user profile image if exist
            if($user->getProfileImage()) {
                /** @var UploadedFile $file */
                $filename = $user->getProfileImage();
                $filePath = $this->getParameter('kernel.project_dir') . '/public/profile/images/' . $filename;
                unlink($filePath);
            }

            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_list');
    }

    #[Route('/disable/{id}', name: '_disable', requirements: ['id' => '\d+'], methods: ['GET'])]
    #[IsGranted("ROLE_ADMIN")]
    public function disable(Request $request, EntityManagerInterface $entityManager,int $id, UserRepository $userRepository): Response
    {
        $user = $userRepository->find($id);
        if ($this->isCsrfTokenValid('disable'.$user->getId(), $request->get('token'))) {
            if($user->isActive()){
                $user->setActive(false);
                $entityManager->flush();
                return $this->redirectToRoute('app_user_list');
            } else {
                $user->setActive(true);
                $entityManager->flush();
                return $this->redirectToRoute('app_user_list');
            }
        }
        return $this->redirectToRoute('app_user_list');
    }
    #[Route('/import', name: '_import', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_ADMIN")]
    public function import(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher,CampusRepository $campusRepository, UserRepository $userRepository): Response
    {

        $form = $this->createForm(CsvUploadType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && $this->isCsrfTokenValid('import', $request->query->get('token'))) {
            $csvFile = $form->get('csv_file')->getData();

            if(filesize($csvFile)<71){
                $this->addFlash('error', 'Votre fichier est vide/imcomplet ou ne contient aucun utilisateur !');
                return $this->redirectToRoute('app_user_import');
            }

            // Vérification de l'extension et du type MIME
            $extension = $csvFile->getClientOriginalExtension();
            $allowedMimeTypes = ['text/csv', 'text/plain'];

            if ($extension !== 'csv' || (!in_array($csvFile->getMimeType(), $allowedMimeTypes))) {
                dd($extension, $csvFile->getMimeType());
                $this->addFlash('error', 'Le type ou extension de votre fichier est invalide. Merci d\'utiliser un fichier .CSV');
                return $this->redirectToRoute('app_user_import');
            }


            try{
                $fileName = uniqid().'.csv';
                $destination = $this->getParameter('csv_directory');
                $csvFile->move($destination, $fileName);
                $filePath = $destination.'/'.$fileName;

                if (($handle = fopen($filePath, 'r')) !== false) {

                    $headersComma = fgetcsv($handle, 1000, ",");
                    rewind($handle);
                    $headersSemiColon = fgetcsv($handle, 1000, ";");
                    $expectedHeaders = ['campus','pseudo','role','mot_de_passe','nom','prenom','telephone','email','est_actif'];

                    if(strpos($headersComma[0],"\u{FEFF}") === 0 || strpos($headersSemiColon[0],"\u{FEFF}") === 0) {
                        $headersComma[0]='campus';
                        $headersSemiColon[0]='campus';
                    }

                    if($expectedHeaders === $headersComma) {
                        $delimiter = ",";
                    }elseif ($expectedHeaders === $headersSemiColon){
                        $delimiter = ";";
                    }else{
                        $this->addFlash('error', 'Entête CSV invalide !');
                        fclose($handle);
                        return $this->redirectToRoute('app_user_import');
                    }

                    while (($data = fgetcsv($handle, 1000, $delimiter)) !== false) {
                        // $data est un tableau des valeurs pour une ligne

                        if($data[0]) {

                            $forbiddenChar = "'(){}[],.;:=~";
                            $isPseudoIncorrect = strpbrk($data[1], $forbiddenChar);
                            if (!$isPseudoIncorrect) {
                                $isPseudoUsed = $userRepository->findOneBy(['pseudo' => $data[1]]);
                            }
                            $isMailUsed = $userRepository->findOneBy(['email' => $data[7]]);
                            $isCampusValid = $campusRepository->findOneBy(['name' => $data[0]]);
                            $isActiveValid = true;
                            $isRoleValid = true;
                            $roles[0] = strtoupper($data[2]);
                            if ($roles[0] === "") {
                                $roles[0] = 'ROLE_USER';
                            }

                            if ($isPseudoIncorrect) {
                                $this->addFlash('error', 'Utilisateur : ' . $data[5] . ' ' . $data[4] . ' le pseudo : ' . $data[1] . ' n\'est pas autorisé ! L\'utilisateur n\'a pas été ajouté !');
                            }
                            if ($isPseudoUsed) {

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Suprimer</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Utilisateurs{% endblock %}

{% block body %}
    <div class="max-w-4xl lg:max-w-3xl mx-auto bg-white-transparent p-8 rounded-lg shadow-lg mb-3 ">
        <h1 class="text-3xl font-extrabold text-gray-800 mb-6 text-center">Modifier Utilisateur</h1>

        {{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {% for field in form %}
                {% if field.vars.name == '_token' %}
                    {# Rendre le champ CSRF caché pour qu'il ne soit pas visible #}
                    {{ form_widget(field) }}
                {% elseif field.vars.name == 'plainPassword' %}
                    <!-- Section séparée pour le mot de passe -->
                    <div class="col-span-1 md:col-span-2">
                        <!-- Section pour le mot de passe -->
                        <div class="form-group mb-4">
                            {{ form_label(field.first, null, {'attr': {'class': 'block text-gray-700 font-medium mb-1'}}) }}
                            {{ form_widget(field.first, {'attr': {'class': 'form-input w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-orange-500 focus:ring-opacity-50'}}) }}
                            {{ form_errors(field.first, {'attr': {'class': 'text-red-600 text-sm mt-1'}}) }}
                        </div>

                        <!-- Section pour la confirmation du mot de passe -->
                        <div class="form-group mb-4">
                            {{ form_label(field.second, null, {'attr': {'class': 'block text-gray-700 font-medium mb-1'}}) }}
                            {{ form_widget(field.second, {'attr': {'class': 'form-input w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-orange-500 focus:ring-opacity-50'}}) }}
                            {{ form_errors(field.second, {'attr': {'class': 'text-red-600 text-sm mt-1'}}) }}
                        </div>
                    </div>
                {% else %}
                    <!-- Autres champs du formulaire -->
                    <div class="form-group mb-4">
                        {{ form_label(field, null, {'attr': {'class': 'block text-gray-700 font-medium mb-1'}}) }}
                        {{ form_widget(field, {'attr': {'class': 'form-input w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:ring-orange-500 focus:ring-opacity-50'}}) }}
                        {{ form_errors(field, {'attr': {'class': 'text-red-600 text-sm mt-1'}}) }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="inline-block px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-md transition-colors duration-300">
                {{ button_label|default('Modifier') }}
            </button>
        </div>

        {{ form_end(form, {'render_rest': false}) }}
    </div>
{% endblock %}

templates/user/import.html.twig
{%  extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Utilisateurs{% endblock %}

{%  block body %}

    <div class="max-w-4xl lg:max-w-3xl mx-auto bg-white-transparent p-8 rounded-lg shadow-lg mb-3">

        <h1 class="text-3xl font-extrabold text-gray-800 mb-10 text-center">Import de nouveaux utilisateurs</h1>

    <div class="flex justify-center items-center mb-3" >
        {{ form_start(form, {'action': path('app_user_import', {'token': csrf_token('import')})}) }}

        {{ form_widget(form.csv_file) }}

        <button
            class="btn btn-primary"
            href="{{ path('app_user_import', {'token':csrf_token('import')}) }}"
            onclick="return confirm('Merci de confirmer l\'ajout d\'utilisateur(s) en cliquant sur OK')">Importer
        </button>

        <div class="flex justify-center items-center bg-red-100 text-red-700 px-4 py-3 rounded relative mx-auto my-2">
                <span class="block sm:inline">{{ form_errors(form.csv_file) }}</span>
        </div>
        {{ form_end(form) }}
    </div>

    <div class="justify-center items-center mx-auto">
        {% for type in ['success'] %}
        {% for message in app.flashes(type) %}
            <div class="flex justify-center items-center bg-green-300 text-green-800 px-4 py-3 rounded relative  mx-auto">
                {{ message }}
                <br>
            </div>

        {% endfor %}
        {% endfor %}

        {% for type in ['error'] %}

            {% for message in app.flashes(type) %}
            <div class="flex justify-center items-center bg-red-100 text-red-700 px-4 py-3 rounded relative mx-auto ">
                <span class="block sm:inline">
                    {{ message }}
                    <br>
                </span>
            </div>

        {% endfor %}

    {% endfor %}

    </div>
    </div>
{%  endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Utilisateurs{% endblock %}

{% block body %}
    <section class="bg-custom min-h-screen text-white">
    <h1 class="text-3xl lg:text-4xl font-extrabold text-gray-800 mb-8">Utilisateurs</h1>
    <div class="m-5">
        <a class="inline-block px-8 py-4 bg-blue-700 text-white font-semibold rounded-full shadow hover:bg-blue-800 transition duration-300" href="{{ path('app_register') }}">Créer</a>
        <a class="inline-block px-8 py-4 bg-blue-700 text-white font-semibold rounded-full shadow hover:bg-blue-800 transition duration-300" href="{{ path('app_user_import') }}">Importer</a>
    </div>
    {%  if is_granted('ROLE_ADMIN') %}
        <div class="flex justify-center">

        <table class="table">
            <thead>
            <tr>
                <th></th>
                <th>Pseudo</th>
                <th>Roles</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Téléphone</th>
                <th>Email</th>
                <th>Actif</th>
                <th>Gérer</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>
                        <a href="{{ path('app_user_profile', {'id': user.id}) }}">
                            <img style="max-height: 30px" src="{{ asset('images/icone-afficher.webp') }}" alt="Afficher" class="mx-auto">
                        </a>
                    </td>
                    <td>{{ user.pseudo }}</td>
                    <td>
                        {% for role in user.roles %}
                            {{ role[5:] }} <br>
                        {% endfor %}
                    </td>
                    <td>{{ user.lastName }}</td>
                    <td>{{ user.firstName }}</td>
                    <td>{{ user.phone }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.isActive ? 'Oui' : 'Non' }}</td>
                    <td>
                        <button><a href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier</a></button>
                        <button><a href="{{ path('app_user_disable', {'id': user.id, 'token': csrf_token('disable'~user.id)}) }}" onclick="return confirm('Voulez-vous vraiment le désactiver/activer ?')">Activer/Désactiver</a></button>
                        <button><a href="{{ path('app_user_delete', {'id': user.id, 'token': csrf_token('delete'~user.id)}) }}" onclick="return confirm('Voulez-vous vraiment le supprimer ?')">Supprimer</a></button>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
        </section>
    {% endif %}
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Utilisateurs{% endblock %}

{% block body %}
    <div>
        <div class="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
            <!-- Section d'Image de Profil -->

            <!-- Informations Utilisateur -->
            <h1 class="text-3xl font-extrabold text-gray-800 mb-4 text-center">Utilisateur</h1>

        <p class="flex justify-center mb-3">
            {% if user.getProfileImage() %}
            <img src="/profile/images/{{ user.profileImage }}" alt="profile picture">
            {% else %}
                <img src="{{ asset('images/defaultProfilePicture.jpg') }}" alt="default profile picture">
            {% endif %}
        </p>

            <table class="min-w-full bg-white divide-y divide-gray-200">
                <tbody class="bg-white divide-y divide-gray-200">
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Pseudo</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.pseudo }}</td>
                </tr>
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Nom</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.lastName }}</td>
                </tr>
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Prénom</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.firstName }}</td>
                </tr>
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Téléphone</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.phone }}</td>
                </tr>
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Mail</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.email }}</td>
                </tr>
                <tr>
                    <th class="py-2 px-4 text-left text-gray-600 font-medium">Site de rattachement :</th>
                    <td class="py-2 px-4 text-gray-800">{{ user.campus.name }}</td>
                </tr>
                </tbody>
            </table>

            <!-- Lien pour Modifier -->
            {% if user.id == app.user.id %}
                <div class="text-center mt-6">
                    <a href="{{ path('app_user_edit') }}" class="inline-block px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow-md transition-colors duration-300">
                        Modifier
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}